language: node_js
node_js:
  - "4"

before_install:
  - sudo apt-get -qq update
#  - sudo apt-get install -y go
  - sudo apt-get install -y hugo

install:
  - (cd hugo; hugo)

# whitelist
branches:
  only:
    - master
    - dev

script:
    "npm run deploy"
