language: node_js
node_js:
  - "4"

before_install:
#  - sudo add-apt-repository
  - sudo apt-get -qq update
  - sudo apt install snapd
#  - sudo apt-get install -y go
#  - sudo apt-get install -y hugo

install:
  - (cd hugo; hugo)

# whitelist
branches:
  only:
    - master
    - dev

script:
    "npm run deploy"
