language: node_js
node_js:
  - "4"

before_install:
#  - sudo add-apt-repository
  - sudo apt-get -qq update
#  - sudo apt install snapd
#  - sudo apt-get install -y go
#  - sudo apt-get install -y hugo
  - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
  - sudo dpkg -i hugo_0.19-64bit.deb

#install:

# whitelist
branches:
  only:
    - master

script:
    - "npm install"
    - "npm run build"
    - "(cd hugo; hugo)"
    - "npm run deploy"
